# Projeto 2 - análise de dados
### Turismo mundial

In [33]:
%matplotlib inline
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import os

In [34]:
print('Esperamos trabalhar no diretório')
print(os.getcwd())

Esperamos trabalhar no diretório
/Users/duddatorres/Documents/Cdados/Projeto-2

In [35]:
dados_turismo = pd.read_excel('Dados_turismo.xlsx',thousands=",")
dados_turismo = dados_turismo.set_index('Country')
dados_turismo.head()

,int inbound 2012,int inbound 2018,int outbound 2012,int outbound 2018,inbound exp 2012 (millions),inbound exp 2018 (millions),inbound exp 2012 (percentage),inbound exp 2018 (percentage),outbound exp 2012 (millions),outbound exp 2018 (millions),outbound exp 2012 (percentage),outbound exp 2018 (percentage)
Country,,,,,,,,,,,,
Afghanistan,NaN,NaN,NaN,NaN,167.0,50.0,7.2,3.1,110.0,226.0,1.1,2.8
Albania,3156.0,534.0,3959.0,5415.0,1623.0,2306.0,45.6,48.2,1374.0,175.0,23.5,25.5
Algeria,2634.0,2657.0,1911.0,561.0,295.0,NaN,0.4,NaN,598.0,NaN,1.0,NaN
American Samoa,23.0,20.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Andorra,2238.0,3042.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [42]:
dados_bio = pd.read_excel('Dados_bio.xlsx')
dados_bio = dados_bio.sort_values('Country')
dados_bio.loc[:,'Country'] = dados_bio.loc[:,'Country'].str.strip()
dados_bio = dados_bio.set_index('Country')
dados_bio.head()

,Bare area,Cropland,Tree cover,Grassland,Shrubland,Sparse vegetation,Artificial surfaces,Inland water,Wetland
Country,,,,,,,,,
Afghanistan,39.1,12.2,1.2,37.3,3.5,6.3,0.1,0.1,0.0
Albania,1.8,49.8,34.8,5.5,3.2,1.4,1.0,2.3,0.3
Algeria,90.1,4.6,0.9,0.0,0.7,3.5,0.1,0.1,0.0
American Samoa,0.0,53.0,32.2,0.0,0.0,0.1,0.2,14.6,0.0
Andorra,4.6,1.0,59.0,23.7,0.0,10.8,0.8,0.0,0.0

In [43]:

dados = dados_turismo.merge(dados_bio, left_index=True, right_index=True)
#dados_turismo.join(dados_bio)
dados

,int inbound 2012,int inbound 2018,int outbound 2012,int outbound 2018,inbound exp 2012 (millions),inbound exp 2018 (millions),inbound exp 2012 (percentage),inbound exp 2018 (percentage),outbound exp 2012 (millions),outbound exp 2018 (millions),...,outbound exp 2018 (percentage),Bare area,Cropland,Tree cover,Grassland,Shrubland,Sparse vegetation,Artificial surfaces,Inland water,Wetland
Country,,,,,,,,,,,,,,,,,,,,,
Afghanistan,NaN,NaN,NaN,NaN,167.0,50.0,7.2,3.1,110.0,226.0,...,2.8,39.1,12.2,1.2,37.3,3.5,6.3,0.1,0.1,0.0
Albania,3156.0,534.0,3959.0,5415.0,1623.0,2306.0,45.6,48.2,1374.0,175.0,...,25.5,1.8,49.8,34.8,5.5,3.2,1.4,1.0,2.3,0.3
Algeria,2634.0,2657.0,1911.0,561.0,295.0,NaN,0.4,NaN,598.0,NaN,...,NaN,90.1,4.6,0.9,0.0,0.7,3.5,0.1,0.1,0.0
American Samoa,23.0,20.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,53.0,32.2,0.0,0.0,0.1,0.2,14.6,0.0
Andorra,2238.0,3042.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,4.6,1.0,59.0,23.7,0.0,10.8,0.8,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Uzbekistan,1895.0,5346.0,NaN,NaN,NaN,1314.0,NaN,9.3,NaN,2722.0,...,11.6,55.6,20.1,0.1,6.1,9.5,5.7,0.8,1.9,0.1
Vanuatu,108.0,116.0,23.0,29.0,268.0,325.0,75.2,62.8,43.0,21.0,...,4.6,0.2,5.0,89.2,0.0,0.0,0.1,0.0,5.5,0.0
Zambia,859.0,1072.0,NaN,NaN,518.0,742.0,4.9,7.4,303.0,478.0,...,4.7,0.0,16.9,62.0,1.6,13.7,0.0,0.1,1.8,3.8
Zimbabwe,1794.0,258.0,720.0,2987.0,174.0,NaN,4.0,NaN,387.0,NaN,...,NaN,0.2,37.3,29.7,3.8,27.6,0.0,0.2,1.1,0.1
World,1070183.0,1441953.0,1179078.0,1563556.0,1275118.0,1649264.0,5.6,6.6,1160710.0,1575316.0,...,6.4,22.9,17.6,29.7,9.3,9.1,7.0,0.5,2.7,1.3

In [44]:
dados.describe()

,int inbound 2012,int inbound 2018,int outbound 2012,int outbound 2018,inbound exp 2012 (millions),inbound exp 2018 (millions),inbound exp 2012 (percentage),inbound exp 2018 (percentage),outbound exp 2012 (millions),outbound exp 2018 (millions),...,outbound exp 2018 (percentage),Bare area,Cropland,Tree cover,Grassland,Shrubland,Sparse vegetation,Artificial surfaces,Inland water,Wetland
count,1.710000e+02,1.520000e+02,9.300000e+01,8.500000e+01,1.650000e+02,1.510000e+02,160.000000,146.000000,1.660000e+02,1.490000e+02,...,147.000000,185.000000,185.000000,185.000000,185.000000,185.000000,185.000000,185.000000,185.000000,185.000000
mean,1.039785e+04,1.698376e+04,1.918390e+04,2.759107e+04,1.383290e+04,1.876917e+04,15.145625,18.154795,1.230922e+04,1.760962e+04,...,7.019048,11.561622,27.953514,33.416216,8.963784,5.942162,2.839459,2.323784,5.868649,1.120000
std,8.199656e+04,1.172879e+05,1.222651e+05,1.695197e+05,1.005099e+05,1.356294e+05,17.521806,20.787775,9.093006e+04,1.299831e+05,...,4.823293,24.973899,21.509333,27.458903,14.127788,11.632038,6.134614,5.940537,13.122926,2.978525
min,1.000000e+00,3.000000e+00,1.500000e+01,2.900000e+01,2.000000e+00,4.000000e+00,0.000000,0.200000,2.000000e+00,4.000000e+00,...,0.200000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2.450000e+02,4.455000e+02,4.930000e+02,8.360000e+02,2.150000e+02,5.120000e+02,3.900000,4.450000,1.335000e+02,2.820000e+02,...,3.850000,0.000000,8.600000,7.800000,0.200000,0.000000,0.000000,0.200000,0.700000,0.000000
50%,1.006000e+03,1.848500e+03,1.816000e+03,2.486000e+03,9.060000e+02,1.921000e+03,7.250000,9.350000,5.945000e+02,9.600000e+02,...,5.900000,0.100000,23.400000,31.800000,3.700000,0.500000,0.100000,0.500000,1.800000,0.100000
75%,3.873000e+03,7.450750e+03,7.454000e+03,9.966000e+03,4.687000e+03,6.123500e+03,19.100000,22.625000,2.917250e+03,5.625000e+03,...,9.100000,4.400000,43.300000,57.700000,11.200000,6.100000,2.800000,1.700000,4.700000,0.700000
max,1.070183e+06,1.441953e+06,1.179078e+06,1.563556e+06,1.275118e+06,1.649264e+06,82.800000,95.200000,1.160710e+06,1.575316e+06,...,25.500000,96.000000,84.700000,96.300000,84.200000,76.900000,36.600000,49.000000,89.400000,29.900000

In [45]:
dados.corr()

,int inbound 2012,int inbound 2018,int outbound 2012,int outbound 2018,inbound exp 2012 (millions),inbound exp 2018 (millions),inbound exp 2012 (percentage),inbound exp 2018 (percentage),outbound exp 2012 (millions),outbound exp 2018 (millions),...,outbound exp 2018 (percentage),Bare area,Cropland,Tree cover,Grassland,Shrubland,Sparse vegetation,Artificial surfaces,Inland water,Wetland
int inbound 2012,1.000000,0.997299,0.996316,0.996803,0.993065,0.991414,-0.058594,-0.064620,0.992698,0.993763,...,-0.018318,0.043124,-0.028733,-0.019300,0.005920,0.028136,0.054935,-0.018810,-0.032058,-0.002557
int inbound 2018,0.997299,1.000000,0.994951,0.995263,0.993312,0.991817,-0.072996,-0.082862,0.992574,0.992987,...,-0.028680,0.044819,-0.019286,-0.026023,0.008397,0.043383,0.047176,-0.022813,-0.040396,-0.006293
int outbound 2012,0.996316,0.994951,1.000000,0.999656,0.991404,0.990110,-0.078346,-0.087442,0.996787,0.996983,...,0.005002,0.065452,-0.081433,-0.031029,0.023110,0.082103,0.054566,-0.025519,-0.026448,0.012217
int outbound 2018,0.996803,0.995263,0.999656,1.000000,0.992269,0.991143,-0.079509,-0.090535,0.996997,0.997236,...,-0.006978,0.052438,-0.073373,-0.029406,0.027756,0.083167,0.049473,-0.032254,-0.028765,0.012452
inbound exp 2012 (millions),0.993065,0.993312,0.991404,0.992269,1.000000,0.997387,-0.060169,-0.067037,0.995508,0.996655,...,-0.019735,0.027149,-0.024585,-0.025018,0.027096,0.031340,0.060020,-0.009216,-0.033629,0.005396
inbound exp 2018 (millions),0.991414,0.991817,0.990110,0.991143,0.997387,1.000000,-0.064464,-0.063104,0.993970,0.995863,...,-0.017800,0.035973,-0.033917,-0.026455,0.020697,0.038052,0.062189,-0.019752,-0.030682,-0.005761
inbound exp 2012 (percentage),-0.058594,-0.072996,-0.078346,-0.079509,-0.060169,-0.064464,1.000000,0.938814,-0.071562,-0.072478,...,0.153569,-0.150930,-0.050497,0.081987,-0.084892,-0.030924,-0.030290,-0.044303,0.305543,-0.008089
inbound exp 2018 (percentage),-0.064620,-0.082862,-0.087442,-0.090535,-0.067037,-0.063104,0.938814,1.000000,-0.077963,-0.072036,...,0.169734,-0.132541,-0.115050,0.102869,-0.085542,-0.004161,-0.039717,-0.056155,0.306105,0.224041
outbound exp 2012 (millions),0.992698,0.992574,0.996787,0.996997,0.995508,0.993970,-0.071562,-0.077963,1.000000,0.999082,...,-0.009835,0.033434,-0.036000,-0.026168,0.029349,0.026671,0.065545,0.000137,-0.032200,0.017091
outbound exp 2018 (millions),0.993763,0.992987,0.996983,0.997236,0.996655,0.995863,-0.072478,-0.072036,0.999082,1.000000,...,-0.006067,0.041895,-0.038746,-0.029631,0.022033,0.029666,0.065235,-0.008512,-0.028327,-0.002966
outbound exp 2012 (percentage),-0.020244,-0.030984,-0.002498,-0.004534,-0.017722,-0.015832,0.248861,0.219992,-0.002929,-0.002124,...,0.831058,0.093717,-0.149739,-0.193538,-0.062182,-0.054241,0.270202,-0.032918,0.417830,0.134922
outbound exp 2018 (percentage),-0.018318,-0.028680,0.005002,-0.006978,-0.019735,-0.017800,0.153569,0.169734,-0.009835,-0.006067,...,1.000000,0.133544,-0.085229,-0.218448,-0.081575,0.061859,0.277197,0.040554,0.242082,0.004755
Bare area,0.043124,0.044819,0.065452,0.052438,0.027149,0.035973,-0.150930,-0.132541,0.033434,0.041895,...,0.133544,1.000000,-0.365944,-0.502829,-0.087163,-0.092069,0.232452,-0.043272,-0.141944,-0.105167
Cropland,-0.028733,-0.019286,-0.081433,-0.073373,-0.024585,-0.033917,-0.050497,-0.115050,-0.036000,-0.038746,...,-0.085229,-0.365944,1.000000,-0.186498,-0.204157,-0.143683,-0.279023,0.149490,-0.097346,-0.193870
Tree cover,-0.019300,-0.026023,-0.031029,-0.029406,-0.025018,-0.026455,0.081987,0.102869,-0.026168,-0.029631,...,-0.218448,-0.502829,-0.186498,1.000000,-0.236918,-0.173036,-0.322971,-0.173796,-0.188332,-0.015034
Grassland,0.005920,0.008397,0.023110,0.027756,0.027096,0.020697,-0.084892,-0.085542,0.029349,0.022033,...,-0.081575,-0.087163,-0.204157,-0.236918,1.000000,0.020872,0.037964,-0.070725,-0.125544,0.178731
Shrubland,0.028136,0.043383,0.082103,0.083167,0.031340,0.038052,-0.030924,-0.004161,0.026671,0.029666,...,0.061859,-0.092069,-0.143683,-0.173036,0.020872,1.000000,0.082101,-0.111973,-0.124620,0.004413
Sparse vegetation,0.054935,0.047176,0.054566,0.049473,0.060020,0.062189,-0.030290,-0.039717,0.065545,0.065235,...,0.277197,0.232452,-0.279023,-0.322971,0.037964,0.082101,1.000000,-0.088097,0.123122,0.114107
Artificial surfaces,-0.018810,-0.022813,-0.025519,-0.032254,-0.009216,-0.019752,-0.044303,-0.056155,0.000137,-0.008512,...,0.040554,-0.043272,0.149490,-0.173796,-0.070725,-0.111973,-0.088097,1.000000,-0.022072,-0.056562
Inland water,-0.032058,-0.040396,-0.026448,-0.028765,-0.033629,-0.030682,0.305543,0.306105,-0.032200,-0.028327,...,0.242082,-0.141944,-0.097346,-0.188332,-0.125544,-0.124620,0.123122,-0.022072,1.000000,0.098566
Wetland,-0.002557,-0.006293,0.012217,0.012452,0.005396,-0.005761,-0.008089,0.224041,0.017091,-0.002966,...,0.004755,-0.105167,-0.193870,-0.015034,0.178731,0.004413,0.114107,-0.056562,0.098566,1.000000

In [46]:
dados.dtypes

int inbound 2012                   float64
int inbound 2018                   float64
int outbound 2012                  float64
int outbound 2018                  float64
inbound exp 2012  (millions)       float64
inbound exp 2018  (millions)       float64
inbound exp 2012  (percentage)     float64
inbound exp 2018  (percentage)     float64
outbound exp 2012  (millions)      float64
outbound exp 2018  (millions)      float64
outbound exp 2012  (percentage)    float64
outbound exp 2018  (percentage)    float64
Bare area                          float64
Cropland                           float64
Tree cover                         float64
Grassland                          float64
Shrubland                          float64
Sparse vegetation                  float64
Artificial surfaces                float64
Inland water                       float64
Wetland                            float64
dtype: object